# 项目相关配置
app:
  # 名称
  name: 工作流平台
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.wei: info
    org.springframework: warn

spring.main.allow-circular-references: true
spring.sleuth.redis.enabled: false

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: ${env:unknown}
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  5MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期(分钟)
  expireTime: 1440

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.wei.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: false
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

qiye:
  weixin:
    weixinApi: https://qyapi.weixin.qq.com/cgi-bin
    sendNewsApi: https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=
    qiyeSecret: JmaJ1_NvWs08HUYZleG4xAQYpFdpDbz48K-a5GIe2nw
    qiyeAppId: ww56a10deec71b70eb
wechat:
  appId: wxea1809c8fb4caabd
  secret: 19898f2cc07be0e0992186e252ce97d8

flowable:
  database-schema-update: true

assist4j:
  sequence-map:
    seqCustomer: seq_customer
    seqSysForm: seq_sys_form
    seqFlowAuthWidget: seq_flow_auth_widget
    seqFlowAuthNodeSetting: seq_flow_auth_node_setting
    seqOrder: seq_order
    seqOrderPort: seq_order_port
    seqOrderDevice: seq_order_device
    seqOrderMplsIpsec: seq_order_mpls_ipsec
    seqOrderSpecialLine: seq_order_special_line
    seqOrderInternet: seq_order_internet
    seqOrderIdc: seq_order_idc
    seqOrderSrv: seq_order_service
    seqOrderIntegration: seq_order_integration
    seqContract: seq_contract
    seqContractOrder: seq_contract_order
    seqContractAttach: seq_contract_attach
    seqImpl: seq_impl
    seqImplOrder: seq_impl_order
    seqSpSupplier: seq_sp_supplier
    seqSpRespBill: seq_sp_resp_bill

